// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductsApi.Data;

namespace ProductsApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210601145355_seedDataAddedAgain")]
    partial class seedDataAddedAgain
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ProductsApi.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            DateCreated = new DateTime(2021, 6, 1, 14, 53, 55, 15, DateTimeKind.Utc).AddTicks(8210),
                            Description = "Most valuable precious metal",
                            Link = "https://responsive.fxempire.com/v7/_fxempire_/2020/06/Gold-11.jpg?func=cover&q70&width=615",
                            Name = "Gold",
                            Price = 12000m
                        },
                        new
                        {
                            ProductId = 2,
                            DateCreated = new DateTime(2021, 6, 1, 14, 53, 55, 15, DateTimeKind.Utc).AddTicks(8880),
                            Description = "Second most valuable precious metal",
                            Link = "https://e7j3v5v7.rocketcdn.me/wp-content/uploads/2020/05/327446-silver-1024x640.jpg",
                            Name = "Silver",
                            Price = 6000m
                        },
                        new
                        {
                            ProductId = 3,
                            DateCreated = new DateTime(2021, 6, 1, 14, 53, 55, 15, DateTimeKind.Utc).AddTicks(8880),
                            Description = "Digital Gold",
                            Link = "https://i.guim.co.uk/img/media/09de088fe70256cfae7c4bc42b6cded754545133/0_66_3500_2100/master/3500.jpg?width=620&quality=85&auto=format&fit=max&s=5d8ef8483e18802012c16ef18a7f9568",
                            Name = "Bitcoin",
                            Price = 40000m
                        },
                        new
                        {
                            ProductId = 4,
                            DateCreated = new DateTime(2021, 6, 1, 14, 53, 55, 15, DateTimeKind.Utc).AddTicks(8890),
                            Description = "Software Consulting",
                            Link = "https://www.xerris.com/images/xerris-logo.svg",
                            Name = "Xerris",
                            Price = 100000m
                        });
                });

            modelBuilder.Entity("ProductsApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
